const userActionTypes = {
    SET_CURRENT_USER:'SET_CURRENT_USER',

    GOOGLE_SIGN_IN_START:'GOOGLE_SIGN_IN_START',
    
    SIGN_IN_SUCCESS:'SIGN_IN_SUCCESS',
    SIGN_IN_FAILIURE:'SIGN_IN_FAILIURE',

    EMAIL_SIGN_IN_START:'EMAIL_SIGN_START',
   
    SIGN_OUT_START:'SIGN_OUT_START',
    SIGN_OUT_SUCCESS:'SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILIURE: 'SIGN_OUT_FAILIURE',

    CHECK_USER_SESSION: 'CHECK_USER_SESSION',

    SIGN_UP_START: 'SIGN_UP_START',
    SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
    SIGN_UP_FAILURE: 'SIGN_UP_FAILURE'
}

export default userActionTypes